name: saltstack-clamav-formula
source: https://github.com/bechtoldt/saltstack-clamav-formula
summary: SaltStack Formula to set up and configure ClamAV, an antivirus engine designed for detecting Trojans, viruses, malware and other malicious threats
todo:
  - add instructions how to use formhelper, add information about it in the formula-docs (dependency), show up alternative?
  - 'table/ matrix: os/salt compatibility (dedicated file)'
  - add list of available states
  - add tests
